<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.2.1
 */

/**
 * Database `quiz_crud`
 */

/* `quiz_crud`.`choices` */
$choices = array(
  array('id' => '1','question_id' => '1','choice_text' => 'Paris','is_correct' => '1'),
  array('id' => '2','question_id' => '1','choice_text' => 'Lyon','is_correct' => '0'),
  array('id' => '3','question_id' => '1','choice_text' => 'Marseille','is_correct' => '0'),
  array('id' => '4','question_id' => '1','choice_text' => 'Bordeaux','is_correct' => '0'),
  array('id' => '5','question_id' => '2','choice_text' => 'La Chine','is_correct' => '0'),
  array('id' => '6','question_id' => '2','choice_text' => 'La Thaïlande','is_correct' => '0'),
  array('id' => '7','question_id' => '2','choice_text' => 'Le Japon','is_correct' => '1'),
  array('id' => '8','question_id' => '2','choice_text' => 'La Corée','is_correct' => '0'),
  array('id' => '9','question_id' => '3','choice_text' => 'Le Sahara','is_correct' => '0'),
  array('id' => '10','question_id' => '3','choice_text' => 'L\'Arctique','is_correct' => '1'),
  array('id' => '11','question_id' => '3','choice_text' => 'Le désert de Gobi','is_correct' => '0'),
  array('id' => '12','question_id' => '3','choice_text' => 'Le Kalahari','is_correct' => '0'),
  array('id' => '13','question_id' => '4','choice_text' => 'Le Nil','is_correct' => '0'),
  array('id' => '14','question_id' => '4','choice_text' => 'L\'Amazonie','is_correct' => '1'),
  array('id' => '15','question_id' => '4','choice_text' => 'Le Mississippi','is_correct' => '0'),
  array('id' => '16','question_id' => '4','choice_text' => 'Le Colorado','is_correct' => '0'),
  array('id' => '17','question_id' => '5','choice_text' => '1789','is_correct' => '1'),
  array('id' => '18','question_id' => '5','choice_text' => '1776','is_correct' => '0'),
  array('id' => '19','question_id' => '5','choice_text' => '1815','is_correct' => '0'),
  array('id' => '20','question_id' => '5','choice_text' => '1848','is_correct' => '0'),
  array('id' => '21','question_id' => '6','choice_text' => 'Louis XIV','is_correct' => '0'),
  array('id' => '22','question_id' => '6','choice_text' => 'Napoléon Bonaparte','is_correct' => '1'),
  array('id' => '23','question_id' => '6','choice_text' => 'Henri IV','is_correct' => '0'),
  array('id' => '24','question_id' => '6','choice_text' => 'Charles de Gaulle','is_correct' => '0'),
  array('id' => '25','question_id' => '7','choice_text' => 'Bataille de Marignan','is_correct' => '0'),
  array('id' => '26','question_id' => '7','choice_text' => 'Bataille de Waterloo','is_correct' => '1'),
  array('id' => '27','question_id' => '7','choice_text' => 'Bataille d\'Austerlitz','is_correct' => '0'),
  array('id' => '28','question_id' => '7','choice_text' => 'Bataille des Nations','is_correct' => '0'),
  array('id' => '29','question_id' => '8','choice_text' => 'Christophe Colomb','is_correct' => '1'),
  array('id' => '30','question_id' => '8','choice_text' => 'Marco Polo','is_correct' => '0'),
  array('id' => '31','question_id' => '8','choice_text' => 'Vasco de Gama','is_correct' => '0'),
  array('id' => '32','question_id' => '8','choice_text' => 'Hernán Cortés','is_correct' => '0'),
  array('id' => '33','question_id' => '9','choice_text' => 'Victor Hugo','is_correct' => '1'),
  array('id' => '34','question_id' => '9','choice_text' => 'Émile Zola','is_correct' => '0'),
  array('id' => '35','question_id' => '9','choice_text' => 'Alexandre Dumas','is_correct' => '0'),
  array('id' => '36','question_id' => '9','choice_text' => 'Gustave Flaubert','is_correct' => '0'),
  array('id' => '37','question_id' => '10','choice_text' => 'Madame Bovary','is_correct' => '0'),
  array('id' => '38','question_id' => '10','choice_text' => 'Le Rouge et le Noir','is_correct' => '1'),
  array('id' => '39','question_id' => '10','choice_text' => 'Les Misérables','is_correct' => '0'),
  array('id' => '40','question_id' => '10','choice_text' => 'La Chartreuse de Parme','is_correct' => '0'),
  array('id' => '41','question_id' => '11','choice_text' => 'L\'Étranger','is_correct' => '1'),
  array('id' => '42','question_id' => '11','choice_text' => 'La Peste','is_correct' => '0'),
  array('id' => '43','question_id' => '11','choice_text' => 'La Chute','is_correct' => '0'),
  array('id' => '44','question_id' => '11','choice_text' => 'Les Justes','is_correct' => '0'),
  array('id' => '45','question_id' => '12','choice_text' => 'Charles Baudelaire','is_correct' => '0'),
  array('id' => '46','question_id' => '12','choice_text' => 'Alfred de Vigny','is_correct' => '0'),
  array('id' => '47','question_id' => '12','choice_text' => 'Alfred de Musset','is_correct' => '0'),
  array('id' => '48','question_id' => '12','choice_text' => 'Paul Verlaine','is_correct' => '1'),
  array('id' => '49','question_id' => '13','choice_text' => 'Hydrogène','is_correct' => '1'),
  array('id' => '50','question_id' => '13','choice_text' => 'Hélium','is_correct' => '0'),
  array('id' => '51','question_id' => '13','choice_text' => 'Oxygène','is_correct' => '0'),
  array('id' => '52','question_id' => '13','choice_text' => 'Carbone','is_correct' => '0'),
  array('id' => '53','question_id' => '14','choice_text' => '299 792 458 m/s','is_correct' => '1'),
  array('id' => '54','question_id' => '14','choice_text' => '150 000 000 m/s','is_correct' => '0'),
  array('id' => '55','question_id' => '14','choice_text' => '3 000 000 m/s','is_correct' => '0'),
  array('id' => '56','question_id' => '14','choice_text' => '30 000 m/s','is_correct' => '0'),
  array('id' => '57','question_id' => '15','choice_text' => 'Isaac Newton','is_correct' => '0'),
  array('id' => '58','question_id' => '15','choice_text' => 'Albert Einstein','is_correct' => '1'),
  array('id' => '59','question_id' => '15','choice_text' => 'Niels Bohr','is_correct' => '0'),
  array('id' => '60','question_id' => '15','choice_text' => 'Galileo Galilei','is_correct' => '0'),
  array('id' => '61','question_id' => '16','choice_text' => 'Mercure','is_correct' => '1'),
  array('id' => '62','question_id' => '16','choice_text' => 'Vénus','is_correct' => '0'),
  array('id' => '63','question_id' => '16','choice_text' => 'Terre','is_correct' => '0'),
  array('id' => '64','question_id' => '16','choice_text' => 'Mars','is_correct' => '0'),
  array('id' => '65','question_id' => '17','choice_text' => 'Albert Einstein','is_correct' => '0'),
  array('id' => '66','question_id' => '17','choice_text' => 'Isaac Newton','is_correct' => '1'),
  array('id' => '67','question_id' => '17','choice_text' => 'Galileo Galilei','is_correct' => '0'),
  array('id' => '68','question_id' => '17','choice_text' => 'Marie Curie','is_correct' => '0'),
  array('id' => '69','question_id' => '18','choice_text' => 'Ohm','is_correct' => '1'),
  array('id' => '70','question_id' => '18','choice_text' => 'Ampère','is_correct' => '0'),
  array('id' => '71','question_id' => '18','choice_text' => 'Volt','is_correct' => '0'),
  array('id' => '72','question_id' => '18','choice_text' => 'Watt','is_correct' => '0'),
  array('id' => '73','question_id' => '19','choice_text' => 'Alexander Graham Bell','is_correct' => '1'),
  array('id' => '74','question_id' => '19','choice_text' => 'Thomas Edison','is_correct' => '0'),
  array('id' => '75','question_id' => '19','choice_text' => 'Nikola Tesla','is_correct' => '0'),
  array('id' => '76','question_id' => '19','choice_text' => 'Guglielmo Marconi','is_correct' => '0'),
  array('id' => '77','question_id' => '20','choice_text' => 'Ag','is_correct' => '1'),
  array('id' => '78','question_id' => '20','choice_text' => 'Au','is_correct' => '0'),
  array('id' => '79','question_id' => '20','choice_text' => 'Pb','is_correct' => '0'),
  array('id' => '80','question_id' => '20','choice_text' => 'Fe','is_correct' => '0'),
  array('id' => '81','question_id' => '21','choice_text' => 'Azote','is_correct' => '1'),
  array('id' => '82','question_id' => '21','choice_text' => 'Oxygène','is_correct' => '0'),
  array('id' => '83','question_id' => '21','choice_text' => 'Dioxyde de carbone','is_correct' => '0'),
  array('id' => '84','question_id' => '21','choice_text' => 'Argon','is_correct' => '0'),
  array('id' => '85','question_id' => '22','choice_text' => 'Magnétisme','is_correct' => '1'),
  array('id' => '86','question_id' => '22','choice_text' => 'Électricité','is_correct' => '0'),
  array('id' => '87','question_id' => '22','choice_text' => 'Optique','is_correct' => '0'),
  array('id' => '88','question_id' => '22','choice_text' => 'Thermique','is_correct' => '0'),
  array('id' => '89','question_id' => '23','choice_text' => 'Pablo Picasso','is_correct' => '0'),
  array('id' => '90','question_id' => '23','choice_text' => 'Vincent van Gogh','is_correct' => '1'),
  array('id' => '91','question_id' => '23','choice_text' => 'Claude Monet','is_correct' => '0'),
  array('id' => '92','question_id' => '23','choice_text' => 'Édouard Manet','is_correct' => '0'),
  array('id' => '93','question_id' => '24','choice_text' => '1914','is_correct' => '1'),
  array('id' => '94','question_id' => '24','choice_text' => '1939','is_correct' => '0'),
  array('id' => '95','question_id' => '24','choice_text' => '1898','is_correct' => '0'),
  array('id' => '96','question_id' => '24','choice_text' => '1925','is_correct' => '0'),
  array('id' => '97','question_id' => '25','choice_text' => 'Anglais','is_correct' => '0'),
  array('id' => '98','question_id' => '25','choice_text' => 'Chinois mandarin','is_correct' => '1'),
  array('id' => '99','question_id' => '25','choice_text' => 'Espagnol','is_correct' => '0'),
  array('id' => '100','question_id' => '25','choice_text' => 'Hindî','is_correct' => '0'),
  array('id' => '101','question_id' => '26','choice_text' => 'Océan Atlantique','is_correct' => '0'),
  array('id' => '102','question_id' => '26','choice_text' => 'Océan Indien','is_correct' => '0'),
  array('id' => '103','question_id' => '26','choice_text' => 'Océan Pacifique','is_correct' => '1'),
  array('id' => '104','question_id' => '26','choice_text' => 'Océan Arctique','is_correct' => '0'),
  array('id' => '105','question_id' => '27','choice_text' => 'Marie Curie','is_correct' => '0'),
  array('id' => '106','question_id' => '27','choice_text' => 'Alexander Fleming','is_correct' => '1'),
  array('id' => '107','question_id' => '27','choice_text' => 'Isaac Newton','is_correct' => '0'),
  array('id' => '108','question_id' => '27','choice_text' => 'Louis Pasteur','is_correct' => '0'),
  array('id' => '109','question_id' => '28','choice_text' => 'Potassium','is_correct' => '1'),
  array('id' => '110','question_id' => '28','choice_text' => 'Krypton','is_correct' => '0'),
  array('id' => '111','question_id' => '28','choice_text' => 'Calcium','is_correct' => '0'),
  array('id' => '112','question_id' => '28','choice_text' => 'Argon','is_correct' => '0'),
  array('id' => '113','question_id' => '29','choice_text' => '5','is_correct' => '0'),
  array('id' => '114','question_id' => '29','choice_text' => '7','is_correct' => '0'),
  array('id' => '115','question_id' => '29','choice_text' => '9','is_correct' => '1'),
  array('id' => '116','question_id' => '29','choice_text' => '11','is_correct' => '0'),
  array('id' => '117','question_id' => '30','choice_text' => 'Agatha Christie','is_correct' => '0'),
  array('id' => '118','question_id' => '30','choice_text' => 'Arthur Conan Doyle','is_correct' => '1'),
  array('id' => '119','question_id' => '30','choice_text' => 'Victor Hugo','is_correct' => '0'),
  array('id' => '120','question_id' => '30','choice_text' => 'Jules Verne','is_correct' => '0'),
  array('id' => '121','question_id' => '31','choice_text' => 'Égypte','is_correct' => '0'),
  array('id' => '122','question_id' => '31','choice_text' => 'Grèce','is_correct' => '0'),
  array('id' => '123','question_id' => '31','choice_text' => 'Jordanie','is_correct' => '1'),
  array('id' => '124','question_id' => '31','choice_text' => 'Italie','is_correct' => '0'),
  array('id' => '125','question_id' => '32','choice_text' => 'Arthur Rimbaud','is_correct' => '0'),
  array('id' => '126','question_id' => '32','choice_text' => 'Paul Verlaine','is_correct' => '0'),
  array('id' => '127','question_id' => '32','choice_text' => 'Victor Hugo','is_correct' => '0'),
  array('id' => '128','question_id' => '32','choice_text' => 'Charles Baudelaire','is_correct' => '1'),
  array('id' => '129','question_id' => '33','choice_text' => 'The Rolling Stones','is_correct' => '0'),
  array('id' => '130','question_id' => '33','choice_text' => 'The Beatles','is_correct' => '1'),
  array('id' => '131','question_id' => '33','choice_text' => 'Pink Floyd','is_correct' => '0'),
  array('id' => '132','question_id' => '33','choice_text' => 'Queen','is_correct' => '0'),
  array('id' => '133','question_id' => '34','choice_text' => 'Le piano','is_correct' => '0'),
  array('id' => '134','question_id' => '34','choice_text' => 'Le saxophone','is_correct' => '1'),
  array('id' => '135','question_id' => '34','choice_text' => 'Le violon','is_correct' => '0'),
  array('id' => '136','question_id' => '34','choice_text' => 'La harpe','is_correct' => '0'),
  array('id' => '137','question_id' => '35','choice_text' => 'Elvis Presley','is_correct' => '0'),
  array('id' => '138','question_id' => '35','choice_text' => 'Michael Jackson','is_correct' => '1'),
  array('id' => '139','question_id' => '35','choice_text' => 'Prince','is_correct' => '0'),
  array('id' => '140','question_id' => '35','choice_text' => 'Freddie Mercury','is_correct' => '0'),
  array('id' => '141','question_id' => '36','choice_text' => 'Adele','is_correct' => '1'),
  array('id' => '142','question_id' => '36','choice_text' => 'Beyoncé','is_correct' => '0'),
  array('id' => '143','question_id' => '36','choice_text' => 'Taylor Swift','is_correct' => '0'),
  array('id' => '144','question_id' => '36','choice_text' => 'Rihanna','is_correct' => '0'),
  array('id' => '145','question_id' => '37','choice_text' => 'Wolfgang Amadeus Mozart','is_correct' => '0'),
  array('id' => '146','question_id' => '37','choice_text' => 'Johann Sebastian Bach','is_correct' => '0'),
  array('id' => '147','question_id' => '37','choice_text' => 'Ludwig van Beethoven','is_correct' => '1'),
  array('id' => '148','question_id' => '37','choice_text' => 'Franz Schubert','is_correct' => '0'),
  array('id' => '149','question_id' => '38','choice_text' => 'Rock','is_correct' => '0'),
  array('id' => '150','question_id' => '38','choice_text' => 'Disco','is_correct' => '0'),
  array('id' => '151','question_id' => '38','choice_text' => 'Hip-hop','is_correct' => '1'),
  array('id' => '152','question_id' => '38','choice_text' => 'Reggae','is_correct' => '0'),
  array('id' => '153','question_id' => '39','choice_text' => 'Do','is_correct' => '0'),
  array('id' => '154','question_id' => '39','choice_text' => 'La','is_correct' => '1'),
  array('id' => '155','question_id' => '39','choice_text' => 'Mi','is_correct' => '0'),
  array('id' => '156','question_id' => '39','choice_text' => 'Sol','is_correct' => '0'),
  array('id' => '157','question_id' => '40','choice_text' => 'Argentine','is_correct' => '0'),
  array('id' => '158','question_id' => '40','choice_text' => 'Espagne','is_correct' => '0'),
  array('id' => '159','question_id' => '40','choice_text' => 'Brésil','is_correct' => '1'),
  array('id' => '160','question_id' => '40','choice_text' => 'Portugal','is_correct' => '0')
);

/* `quiz_crud`.`questions` */
$questions = array(
  array('id' => '1','quiz_id' => '1','question_text' => 'Quelle est la capitale de la France ?'),
  array('id' => '2','quiz_id' => '1','question_text' => 'Quel pays est surnommé "le pays du soleil levant" ?'),
  array('id' => '3','quiz_id' => '1','question_text' => 'Quel est le plus grand désert du monde ?'),
  array('id' => '4','quiz_id' => '1','question_text' => 'Quel est le fleuve le plus long d\'Amérique du Sud ?'),
  array('id' => '5','quiz_id' => '2','question_text' => 'En quelle année la Révolution française a-t-elle débuté ?'),
  array('id' => '6','quiz_id' => '2','question_text' => 'Qui était l\'empereur de France en 1804 ?'),
  array('id' => '7','quiz_id' => '2','question_text' => 'Quelle bataille a marqué la défaite finale de Napoléon ?'),
  array('id' => '8','quiz_id' => '2','question_text' => 'Qui a découvert l\'Amérique en 1492 ?'),
  array('id' => '9','quiz_id' => '3','question_text' => 'Qui est l\'auteur des Misérables ?'),
  array('id' => '10','quiz_id' => '3','question_text' => 'Dans quel roman trouve-t-on le personnage de Julien Sorel ?'),
  array('id' => '11','quiz_id' => '3','question_text' => 'Quel roman d\'Albert Camus commence par la phrase "Aujourd\'hui, maman est morte" ?'),
  array('id' => '12','quiz_id' => '3','question_text' => 'Quel poète est surnommé "le prince des poètes" au XIXe siècle ?'),
  array('id' => '13','quiz_id' => '4','question_text' => 'Quel est le premier élément du tableau périodique ?'),
  array('id' => '14','quiz_id' => '4','question_text' => 'Quelle est la vitesse de la lumière dans le vide ?'),
  array('id' => '15','quiz_id' => '4','question_text' => 'Qui a formulé la théorie de la relativité ?'),
  array('id' => '16','quiz_id' => '4','question_text' => 'Quelle planète est la plus proche du Soleil ?'),
  array('id' => '17','quiz_id' => '4','question_text' => 'Quel scientifique est célèbre pour ses trois lois du mouvement ?'),
  array('id' => '18','quiz_id' => '4','question_text' => 'Quelle est l\'unité de mesure de la résistance électrique ?'),
  array('id' => '19','quiz_id' => '4','question_text' => 'Qui a inventé le premier téléphone ?'),
  array('id' => '20','quiz_id' => '4','question_text' => 'Quel est le symbole chimique de l\'argent ?'),
  array('id' => '21','quiz_id' => '4','question_text' => 'Quel gaz est le plus abondant dans l\'atmosphère terrestre ?'),
  array('id' => '22','quiz_id' => '4','question_text' => 'Quelle technologie est utilisée pour enregistrer des données sur des disques durs ?'),
  array('id' => '23','quiz_id' => '5','question_text' => 'Qui a peint "La Nuit étoilée" ?'),
  array('id' => '24','quiz_id' => '5','question_text' => 'En quelle année la première Guerre mondiale a-t-elle commencé ?'),
  array('id' => '25','quiz_id' => '5','question_text' => 'Quelle est la langue la plus parlée au monde ?'),
  array('id' => '26','quiz_id' => '5','question_text' => 'Quel est le plus grand océan de la planète ?'),
  array('id' => '27','quiz_id' => '5','question_text' => 'Qui a découvert la pénicilline ?'),
  array('id' => '28','quiz_id' => '5','question_text' => 'Quel est l\'élément chimique dont le symbole est "K" ?'),
  array('id' => '29','quiz_id' => '5','question_text' => 'Combien y a-t-il de symphonies composées par Beethoven ?'),
  array('id' => '30','quiz_id' => '5','question_text' => 'Quel écrivain est connu pour le personnage de "Sherlock Holmes" ?'),
  array('id' => '31','quiz_id' => '5','question_text' => 'Dans quel pays se trouve la ville de Petra, célèbre pour ses constructions taillées dans la roche ?'),
  array('id' => '32','quiz_id' => '5','question_text' => 'Qui a écrit "Les Fleurs du mal" ?'),
  array('id' => '33','quiz_id' => '6','question_text' => 'Quel groupe britannique a sorti l\'album "Abbey Road" en 1969 ?'),
  array('id' => '34','quiz_id' => '6','question_text' => 'Quel instrument est principalement utilisé dans le jazz ?'),
  array('id' => '35','quiz_id' => '6','question_text' => 'Qui est surnommé le "Roi de la Pop" ?'),
  array('id' => '36','quiz_id' => '6','question_text' => 'Quelle chanteuse est connue pour ses chansons "Rolling in the Deep" et "Someone Like You" ?'),
  array('id' => '37','quiz_id' => '6','question_text' => 'Quel compositeur est célèbre pour ses symphonies, dont la 9ème est l\'"Ode à la Joie" ?'),
  array('id' => '38','quiz_id' => '6','question_text' => 'Quel genre musical est né aux États-Unis dans les années 1970 et est connu pour son rythme syncopé ?'),
  array('id' => '39','quiz_id' => '6','question_text' => 'Quelle est la note qui correspond à 440 Hz en fréquence ?'),
  array('id' => '40','quiz_id' => '6','question_text' => 'Dans quel pays est né le style musical "Samba" ?')
);

/* `quiz_crud`.`quizzes` */
$quizzes = array(
  array('id' => '1','title' => 'Géographie','description' => 'Testez vos connaissances sur les pays et les capitales du monde.','slug' => 'geographie'),
  array('id' => '2','title' => 'Histoire','description' => 'Connaissez-vous les dates et les événements marquants de l\'histoire ?','slug' => 'histoire'),
  array('id' => '3','title' => 'Littérature','description' => 'Un quiz pour tester vos connaissances sur les classiques de la littérature française.','slug' => 'litterature'),
  array('id' => '4','title' => 'Science et Technologie','description' => 'Mettez à l\'épreuve vos connaissances en science et technologie avancées.','slug' => 'science-et-technologie'),
  array('id' => '5','title' => 'Culture Générale','description' => 'Testez vos connaissances générales avec des questions difficiles couvrant plusieurs sujets.','slug' => 'culture-generale'),
  array('id' => '6','title' => 'Musique','description' => 'Testez vos connaissances sur la musique, les genres, les instruments et les artistes célèbres.','slug' => 'musique')
);

/* `quiz_crud`.`results` */
$results = array(
);

/* `quiz_crud`.`users` */
$users = array(
);
